extra = {
  "china": [{"name": "Wonton Soup", "price": 6, "stock": 0, "sold": 0},{"name": "Kung Pao Chicken", "price": 4, "stock": 0, "sold": 0},{"name": "Mapo Doufu", "price": 6, "stock": 0, "sold": 0}, {"name": "Rougamo", "price": 4, "stock": 0, "sold": 0}],
  "france": [{"name": "Lemon Meringue Pie", "price": 6, "stock": 0, "sold": 0}, {"name": "Éclair", "price": 3, "stock": 0, "sold": 0}, {"name": "Yule Log", "price": 7, "stock": 0, "sold": 0}, {"name": "Flamiche", "price": 4, "stock": 0, "sold": 0}],
  "greece": [{"name": "Baklava", "price": 4, "stock": 0, "sold": 0}, {"name": "Mousakka", "price": 6, "stock": 0, "sold": 0},{"name": "Octopus", "price": 6, "sell": 0, "sold": 0}, {"name": "Tarama", "price": 4, "stock": 0, "sold": 0}],
  "india": [{"name": "Chicken 65", "price": 5, "stock": 0, "sold": 0}, {"name": "Dhokla", "price": 5, "stock": 0, "sold": 0}, {"name": "Dosa", "price": 6, "stock": 0, "sold": 0}, {"name": "Roti", "price": 4, "stock": 0, "sold": 0}],
  "italy": [{"name": "Risotto", "price": 6, "stock": 0, "sold": 0}, {"name": "Gelato", "price": 5, "stock": 0, "sold": 0}, {"name": "Panini", "price": 5, "stock": 0, "sold": 0}, {"name": "Tiramisu", "price": 4, "stock": 0, "sold": 0}],
  "japan": [{"name": "Udon", "price": 6, "stock": 0, "sold": 0}, {"name": "Onigiri", "price": 4, "stock": 0, "sold": 0}, {"name": "Teriyaki Chicken", "price": 6, "stock": 0, "sold": 0}, {"name": "Bentou", "price": 4, "stock": 0, "sold": 0}],
  "mexico": [{"name": "Chips and Salsa", "price": 4, "stock": 0, "sold": 0}, {"name": "Tamale", "price": 6, "stock": 0, "sold": 0}, {"name": "Chilaquiles", "price": 6, "stock": 0, "sold": 0}, {"name": "Tres Leches", "price": 4, "stock": 0, "sold": 0}],
  "turkey": [{"name": "Ashure", "price": 5, "stock": 0, "sold": 0}, {"name": "Pilaf", "price": 3, "stock": 0, "sold": 0}, {"name": "Jerky", "price": 5, "stock": 0, "sold": 0}, {"name": "Basturma", "price": 6, "stock": 0, "sold": 0}],
  "united kingdom": [{"name": "Shepherd's Pie", "price": 5, "stock": 0, "sold": 0}, {"name": "Bangers and Mash", "price": 6, "stock": 0, "sold": 0}, {"name": "Yorkshire Pudding", "price": 5, "stock": 0, "sold": 0}, {"name": "Apple Cider", "price": 4, "stock": 0, "sold": 0}],
  "united states": [{"name": "Meatloaf", "price": 5, "stock": 0, "sold": 0}, {"name": "Apple Pie", "price": 5, "stock": 0, "sold": 0}, {"name": "Buffalo Wings", "price": 6, "stock": 0, "sold": 0}, {"name": "Tater Tot", "price": 6, "stock": 0, "sold": 0}]
}
