food = [
  {"china": [{"name": "Sweet & Sour Chicken", "price": 8, "stock": 0, "sold": 0}, {"name": "Fried Rice", "price": 6, "stock": 0, "sold": 0}, {"name": "Spring Rolls", "price": 5, "stock": 0, "sold": 0}, {"name": "Chinese Dumplings", "price": 6, "stock": 0, "sold": 0}, {"name": "Prawn Crackers", "price": 4, "stock": 0, "sold": 0}, {"name": "Chow Mein", "price": 9, "stock": 0, "sold": 0}, {"name": "Egg Tart", "price": 4, "stock": 0, "sold": 0}, {"name": "Duck Rolls", "price": 6, "stock": 0, "sold": 0}, {"name": "Mooncake", "price": 7, "stock": 0, "sold": 0}, {"name": "Chai (tea)", "price": 4, "stock": 0, "sold": 0}, {"name": "Bubble Tea", "price": 5, "stock": 0, "sold": 0}, {"name": "Red Wine", "price": 7, "stock": 0, "sold": 0}],
  {"france": [{"name": "Croissants", "price": 5, "stock": 0, "sold": 0}, {"name": "Ratatouille", "price": 12, "stock": 0, "sold": 0}, {"name": "Cheese Soufflé", "price": 7, "stock": 0, "sold": 0}, {"name": "Baguette", "price": 4, "stock": 0, "sold": 0}, {"name": "Rillete", "price": 5, "stock": 0, "sold": 0}, {"name": "Beef Bourguignon", "price": 7, "stock": 0, "sold": 0}, {"name": "Crêpe", "price": 7, "stock": 0, "sold": 0}, {"name": "Crème brûlée", "price": 5, "stock": 0, "sold": 0}, {"name": "Macarons", "price": 5, "stock": 0, "sold": 0}, {"name": "Champagne", "price": 9, "stock": 0, "sold": 0}, {"name": "Coffee", "price": 2, "stock": 0, "sold": 0}, {"name": "Camomille Tea", "price": 4, "stock": 0, "sold": 0}],
  {"greece": [{"name": "Pita Bread", "price": 5, "stock": 0, "sold": 0}, {"name": "Kebab", "price": 8, "stock": 0, "sold": 0}, {"name": "Olives", "price": 3, "stock": 0, "sold": 0}, {"name": "Greek Salad", "price": 6, "stock": 0, "sold": 0}, {"name": "Meat Pie", "price": 8, "stock": 0, "sold": 0}, {"name": "Calamari", "price": 6, "stock": 0, "sold": 0}, {"name": "Mussels", "price": 10, "stock": 0, "sold": 0}, {"name": "Gyro", "price": 9, "stock": 0, "sold": 0}, {"name": "Greek Yogurt", "price": 6, "stock": 0, "sold": 0}, {"name": "Ouzo", "price": 6, "stock": 0, "sold": 0}, {"name": "Greek Tea", "price": 4, "stock": 0, "sold": 0}, {"name": "Gazoza", "price": 3, "stock": 0, "sold": 0}],
  {"india": [{"name": "Curry", "price": 8, "stock": 0, "sold": 0}, {"name": "Samosas", "price": 5, "stock": 0, "sold": 0}, {"name": "Tandoori Chicken", "price": 7, "stock": 0, "sold": 0}, {"name": "Naan Bread", "price": 5, "stock": 0, "sold": 0}, {"name": "Papadums", "price": 5, "stock": 0, "sold": 0}, {"name": "Biriyani", "price": 9, "stock": 0, "sold": 0}, {"name": "Onion Bahji", "price": 6, "stock": 0, "sold": 0}, {"name": "Kheer", "price": 6, "stock": 0, "sold": 0}, {"name": "Coconut Water", "price": 3, "stock": 0, "sold": 0}, {"name": "Lassi", "price": 10, "stock": 0, "sold": 0}, {"name": "Thandai", "price": 8, "stock": 0, "sold": 0}],
  {"italy": [{"name": "Pizza", "price": 5, "stock": 0, "sold": 0}, {"name": "Spaghetti Bolognese", "price": 8, "stock": 0, "sold": 0}, {"name": "Spaghetti and Meatballs", "price": 8, "stock": 0, "sold": 0}, {"name": "Italian Salad", "price": 5, "stock": 0, "sold": 0}, {"name": "Lasagna", "price": 7, "stock": 0, "sold": 0}, {"name": "Ravioli", "price": 8, "stock": 0, "sold": 0}, {"name": "Calzone", "price": 10, "stock": 0, "sold": 0}, {"name": "Garlic Bread", "price": 5, "stock": 0, "sold": 0}, {"name": "Cannoli", "price": 3, "stock": 0, "sold": 0}, {"name": "Campari", "price": 10, "stock": 0, "sold": 0}, {"name": "Italian Soda", "price": 2, "stock": 0, "sold": 0}, {"name": "Prosecco", "price": 10, "stock": 0, "sold": 0}],
  {"japan": [{"name": "Ramen Noodles", "price": 7, "stock": 0, "sold": 0}, {"name": "Sushi Rolls", "price": 5, "stock": 0, "sold": 0}, {"name": "Sashimi", "price": 8, "stock": 0, "sold": 0}, {"name": "Prawn Tempura", "price": 8, "stock": 0, "sold": 0}, {"name": "Yakitori", "price": 7, "stock": 0, "sold": 0}, {"name": "Ikura", "price": 9, "stock": 0, "sold": 0}, {"name": "Miso Soup", "price": 5, "stock": 0, "sold": 0}, {"name": "Dango", "price": 5, "stock": 0, "sold": 0}, {"name": "Mochi", "price": 6, "stock": 0, "sold": 0}, {"name": "Ramune", "price": 2, "stock": 0, "sold": 0}, {"name": "Sake", "price": 4, "stock": 0, "sold": 0}, {"name": "Melon Soda", "price": 2, "stock": 0, "sold": 0}],
  {"mexico": [{"name": "Burrito", "price": 7, "stock": 0, "sold": 0}, {"name": "Taco", "price": 6, "stock": 0, "sold": 0}, {"name": "Nachos", "price": 5, "stock": 0, "sold": 0}, {"name": "Chili con Carne", "price": 8, "stock": 0, "sold": 0}, {"name": "Grilled Corn", "price": 6, "stock": 0, "sold": 0}, {"name": "Quesadilla", "price": 8, "stock": 0, "sold": 0}, {"name": "Fajitas", "price": 7, "stock": 0, "sold": 0}, {"name": "Empanada", "price": 6, "stock": 0, "sold": 0}, {"name": "Churros", "price": 5, "stock": 0, "sold": 0}, {"name": "Tequila", "price": 10, "stock": 0, "sold": 0}, {"name": "Margarita", "price": 9, "stock": 0, "sold": 0}, {"name": "Agua fresca", "price": 2, "stock": 0, "sold": 0}],
  {"united kingdom": [{"name": "Tomato Soup", "price": 5, "stock": 0, "sold": 0}, {"name": "Salad", "price": 6, "stock": 0, "sold": 0}, {"name": "Chicken Wrap", "price": 7, "stock": 0, "sold": 0}, {"name": "Roast Chicken", "price": 11, "stock": 0, "sold": 0}, {"name": "Fish and Chips", "price": 9, "stock": 0, "sold": 0}, {"name": "Vegetable Soup", "price": 7, "stock": 0, "sold": 0}, {"name": "All-Day English Breakfast", "price": 9, "stock": 0, "sold": 0}, {"name": "English Muffin", "price": 5, "stock": 0, "sold": 0}, {"name": "Sponge Cake", "price": 7, "stock": 0, "sold": 0}, {"name": "Tea", "price": 4, "stock": 0, "sold": 0}, {"name": "Ginger Beer", "price": 6, "stock": 0, "sold": 0}, {"name": "Orange Juice", "price": 3, "stock": 0, "sold": 0}],
  {"united states": [{"name": "Cheeseburger", "price": 5, "stock": 0, "sold": 0}, {"name": "Hot Dog", "price": 4, "stock": 0, "sold": 0}, {"name": "Onion Rings", "price": 6, "stock": 0, "sold": 0}, {"name": "BBQ Ribs", "price": 7, "stock": 0, "sold": 0}, {"name": "Chicken Wings", "price": 7, "stock": 0, "sold": 0}, {"name": "Lobster", "price": 10, "stock": 0, "sold": 0}, {"name": "Corn Dog", "price": 4, "stock": 0, "sold": 0}, {"name": "Waffles", "price": 6, "stock": 0, "sold": 0}, {"name": "Donut", "price": 2, "stock": 0, "sold": 0}, {"name": "Lemonade", "price": 4, "stock": 0, "sold": 0}, {"name": "Iced Tea", "price": 3, "stock": 0, "sold": 0}, {"name": "Root Beer", "price": 2, "stock": 0, "sold": 0}]
]

