lyrics = [
  {"lyric": "Hello from the other side", "song": "Hello"},
  {"lyric": "I got a feeling that tonight's gonna be a good night", "song": "I Gotta Feeling"},
  {"lyric": "Cause, baby, you're a firework", "song": "Firework"},
  {"lyric": "I'm in love with the shape of you", "song": "Shape of You"},
  {"lyric": "Is it too late now to say sorry?", "song": "Sorry"},
  {"lyric": "Just gonna stand there and watch me burn", "song": "Love The Way You Lie"},
  {"lyric": "We found love in a hopeless place", "song": "We Found Love"},
  {"lyric": "Cause you make me feel like I've been locked out of heaven", "song": "Locked Out of Heaven"},
  {"lyric": "So wake me up when it's all over", "song": "Wake Me Up"},
  {"lyric": "All of me loves all of you", "song": "All of Me"},
  {"lyric": "But I'm a creep, I'm a weirdo", "song": "Creep"},
  {"lyric": "It's a beautiful day, don't let it get away", "song": "Beautiful Day"},
  {"lyric": "You can dance, you can jive", "song": "Dancing Queen"},
  {"lyric": "Sweet dreams are made of this", "song": "Sweet Dreams (Are Made of This)"},
  {"lyric": "You're the one that I want", "song": "You're the One That I Want"},
  {"lyric": "I'm Slim Shady, yes I'm the real Shady", "song": "The Real Slim Shady"},
  {"lyric": "And I will always love you", "song": "I Will Always Love You"},
  {"lyric": "Shake it off, shake it off", "song": "Shake It Off"},
  {"lyric": "Tonight we are young", "song": "We Are Young"},
  {"lyric": "I kissed a girl and I liked it", "song": "I Kissed a Girl"},
  {"lyric": "Call me maybe", "song": "Call Me Maybe"},
  {"lyric": "Don't stop believin'", "song": "Don't Stop Believin'"},
  {"lyric": "All the single ladies, now put your hands up", "song": "Single Ladies"},
  {"lyric": "Never gonna give you up", "song": "Never Gonna Give You Up"},
  {"lyric": "Is this the real life? Is this just fantasy?", "song": "Bohemian Rhapsody"},
  {"lyric": "She got eyes of the bluest skies", "song": "Sweet Child O' Mine"},
  {"lyric": "Oops, I did it again", "song": "Oops!... I Did It Again"},
  {"lyric": "It's my life, it's now or never", "song": "It's My Life"},
  {"lyric": "Cause I'm happy", "song": "Happy"},
  {"lyric": "Every breath you take", "song": "Every Breath You Take"},
  {"lyric": "I'm walking on sunshine", "song": "Walking on Sunshine"},
  {"lyric": "Billie Jean is not my lover", "song": "Billie Jean"},
  {"lyric": "Another one bites the dust", "song": "Another One Bites the Dust"},
  {"lyric": "Take me home, country roads", "song": "Take Me Home, Country Roads"},
  {"lyric": "She will be loved", "song": "She Will Be Loved"},
  {"lyric": "I can't feel my face when I'm with you", "song": "Can't Feel My Face"},
  {"lyric": "Rolling in the deep", "song": "Rolling in the Deep"},
  {"lyric": "It's a party in the USA", "song": "Party in the U.S.A."},
  {"lyric": "Shot through the heart, and you're to blame", "song": "You Give Love a Bad Name"},
  {"lyric": "You are my fire, the one desire", "song": "I Want It That Way"},
  {"lyric": "And we're gonna let it burn, burn, burn", "song": "Burn"},
  {"lyric": "We're up all night to get lucky", "song": "Get Lucky"},
  {"lyric": "Say my name, say my name", "song": "Say My Name"},
  {"lyric": "It's raining men", "song": "It's Raining Men"},
  {"lyric": "We could have had it all", "song": "Rolling in the Deep"},
  {"lyric": "Isn't she lovely", "song": "Isn't She Lovely"},
  {"lyric": "Welcome to the Hotel California", "song": "Hotel California"},
  {"lyric": "Life is a highway", "song": "Life Is a Highway"},
  {"lyric": "Eye of the tiger, it's the thrill of the fight", "song": "Eye of the Tiger"},
  {"lyric": "I wanna hold your hand", "song": "I Want to Hold Your Hand"},
  {"lyric": "She's got a smile that it seems to me", "song": "Sweet Child O' Mine"},
  {"lyric": "I see trees of green, red roses too", "song": "What a Wonderful World"},
  {"lyric": "Just beat it", "song": "Beat It"},
  {"lyric": "We're all in this together", "song": "We're All In This Together"},
  {"lyric": "Strumming my pain with his fingers", "song": "Killing Me Softly"},
  {"lyric": "You're insecure, don't know what for", "song": "What Makes You Beautiful"},
  {"lyric": "We don't need no education", "song": "Another Brick in the Wall"},
  {"lyric": "I see a little silhouetto of a man", "song": "Bohemian Rhapsody"},
  {"lyric": "Come on, come on, turn the radio on", "song": "Cheap Thrills"},
  {"lyric": "I will survive, oh as long as I know how to love", "song": "I Will Survive"},
  {"lyric": "It's the eye of the tiger, it's the thrill of the fight", "song": "Eye of the Tiger"},
  {"lyric": "I came in like a wrecking ball", "song": "Wrecking Ball"},
  {"lyric": "I need somebody to love", "song": "Somebody to Love"},
  {"lyric": "And I think to myself, what a wonderful world", "song": "What a Wonderful World"},
  {"lyric": "Working 9 to 5, what a way to make a livin'", "song": "9 to 5"},
  {"lyric": "You spin me right round, baby, right round"},
  {"lyric": "I want your love and all your lover's revenge", "song": "Bad Romance"},
  {"lyric": "I wanna hold 'em like they do in Texas, please", "song": "Poker Face"},
  {"lyric": "I'm your biggest fan, I'll follow you until you love me", "song": "Paparazzi"},
  {"lyric": "I'm on the edge of glory", "song": "The Edge of Glory"},
  {"lyric": "Turn around, every now and then I get a little bit lonely", "song": "Total Eclipse of the Heart"},
  {"lyric": "She wears short skirts, I wear T-shirts", "song": "You Belong With Me"},
  {"lyric": "We're caught in a trap, I can't walk out", "song": "Suspicious Minds"},
  {"lyric": "In west Philadelphia, born and raised", "song": "The Fresh Prince of Bel-Air"},
  {"lyric": "I see a bad moon rising", "song": "Bad Moon Rising"},
  {"lyric": "She's in love with the boy", "song": "She's in Love With the Boy"},
  {"lyric": "You shook me all night long", "song": "You Shook Me All Night Long"},
  {"lyric": "I've paid my dues, time after time", "song": "We Are the Champions"},
  {"lyric": "I see skies of blue and clouds of white", "song": "What a Wonderful World"},
  {"lyric": "We all live in a yellow submarine", "song": "Yellow Submarine"},
  {"lyric": "I bless the rains down in Africa", "song": "Africa"},
  {"lyric": "Oh, I wanna dance with somebody", "song": "I Wanna Dance with Somebody"},
  {"lyric": "Tell me somethin', girl, are you happy in this modern world?", "song": "Shallow"},
  {"lyric": "You are the dancing queen, young and sweet, only seventeen", "song": "Dancing Queen"},
  {"lyric": "It's a beautiful night, we're looking for something dumb to do", "song": "Marry You"},
  {"lyric": "You know it's not the same as it was", "song": "As It Was"},
  {"lyric": "I see a little silhouetto of a man", "song": "Bohemian Rhapsody"},
  {"lyric": "You may say I'm a dreamer", "song": "Imagine"},
  {"lyric": "Don't stop me now, I'm having such a good time", "song": "Don't Stop Me Now"},
  {"lyric": "Is this the real life? Is this just fantasy?", "song": "Bohemian Rhapsody"},
  {"lyric": "You're beautiful, you're beautiful, it's true", "song": "You're Beautiful"},
  {"lyric": "Just a small town girl, living in a lonely world", "song": "Don't Stop Believin'"},
  {"lyric": "Take on me, take me on", "song": "Take on Me"},
  {"lyric": "I'm starting with the man in the mirror", "song": "Man in the Mirror"},
  {"lyric": "Baby, you're all that I want, when you're lyin' here in my arms", "song": "Heaven"},
  {"lyric": "Every move you make, every step you take", "song": "Every Breath You Take"},
  {"lyric": "I can't live if living is without you", "song": "Without You"},
  {"lyric": "Some people want it all, but I don't want nothing at all", "song": "If I Ain't Got You"},
  {"lyric": "Don't listen to a word I say, the screams all sound the same", "song": "Little Talks"},
  {"lyric": "I’m gonna swing from the chandelier", "song": "Chandelier"},
  {"lyric": "My mama don't like you and she likes everyone", "song": "Love Yourself"},
  {"lyric": "Loyalty, got royalty inside my DNA", "song": "DNA"},
  {"lyric": "My head's underwater but I'm breathing fine", "song": "All of Me"},
  {"lyric": "I'm in the corner, watching you kiss her", "song": "Dancing On My Own"},
  {"lyric": "Say you'll remember me standing in a nice dress", "song": "Wildest Dreams"},
  {"lyric": "If you love me, let me go", "song": "This Is Gospel"},
  {"lyric": "In the middle of the night, in my dreams", "song": "...Ready For It?"},
  {"lyric": "Cause darling, I'm a nightmare dressed like a daydream", "song": "Blank Space"},
  {"lyric": "I'm gonna love ya until you hate me", "song": "Black Widow"},
  {"lyric": "This is the part when I say I don't want ya", "song": "Break Free"},
  {"lyric": "You're gonna hear me roar", "song": "Roar"},
  {"lyric": "You're my end and my beginning", "song": "All of Me"},
  {"lyric": "You ain't gotta go to work, work, work, work, work, work", "song": "Work From Home"},
  {"lyric": "So baby pull me closer in the backseat of your Rover", "song": "Closer"},
  {"lyric": "I took a pill in Ibiza to show Avicii I was cool", "song": "I Took a Pill in Ibiza"}
]
