questions = [
{"question": "What is the national liquor of America?", "answers": ["Beer", "Red Wine", "Bourbon", "Whisky"], "correct":"Bourbon"},
{"question": "What is the national dish of Italy?", "answers": ["Spaghetti", "Pizza", "Linguine", "Bolognese"], "correct":"Bolognese"},
{"question": "\"I'm lovin' it\" is the slogan of which restaurant?", "answers": ["Taco Bell", "McDonalds", "Pizza Hut", "KFC"], "correct":"McDonalds"},
{"question": "What is the most popular food in the world?", "answers": ["Chicken", "Pizza", "Rice", "French Fries"], "correct":"Chicken"},
{"question": "What happens if you put a rotten egg in water?", "answers": ["It will float", "It will sink", "It will stay in the middle"], "correct":"It will float"},
{"question": "Which country serves as the home of the largest farm in the world?", "answers": ["United States", "Japan", "Mexico", "China"], "correct":"China"},
{"question": "What ingredient in bread causes it to rise?", "answers": ["Yeast", "Gluten", "Flour", "Salt"], "correct":"Yeast"},
{"question": "Which of the following is not a name for a hot dog?", "answers": ["Frankfurter", "Wiener", "Weenie", "Porker Stick"], "correct":"Porker Stick"},
{"question": "Potato chips/crisps were originally called what?", "answers": ["Potato Thins", "Potato Skins", "Saratoga Chips", "Charleston Chips"], "correct":"Saratoga Chips"},
{"question": "In movies and literature, which herb is often used as a weapon to kill vampires?", "answers": ["Thymes", "Garlic", "Chamomile", "Rosemary"], "correct":"Garlic"},
{"question": "In which country did tacos originate?", "answers": ["Spain", "Mexico", "Ecuador", "United States"], "correct":"Mexico"},
{"question": "Which fruit was considered poisonous in Medieval times?", "answers": ["Raspberry", "Cherry", "Watermelon", "Tomato"], "correct":"Tomato"},
{"question": "In which country did paella originate?", "answers": ["Spain", "Mexico", "Ecuador", "United States"], "correct":"Spain"},
{"question": "Where did the pineapple plant originate?", "answers": ["Hawaii", "South America", "Mexico", "Asia"], "correct":"South America"},
{"question": "People used to salt meat taken on ships so it would stay good longer.", "answers": ["True", "False"], "correct":"True"},
{"question": "What is cinnamon made out of?", "answers": ["Tree Bark", "Leaves", "Cinnmaum Plant", "Salt and Ginger"], "correct":"Tree Bark"},
{"question": "Where did Iced Tea Originate?", "answers": ["United Kingdom", "China", "Japan", "United States"], "correct":"United States"},
{"question": "In ancient China, which meat was reserved only for the Emperor?", "answers": ["Chicken", "Pork", "Beef", "Mutton"], "correct":"Pork"},
{"question": "In which country did sushi originate?", "answers": ["China", "Japan", "France", "Malaysia"], "correct":"Japan"},
{"question": "Immersing food in vinegar to prolong its lifespan is known as what?", "answers": ["Vinaigrette", "Pickling", "Salting", "Savouring"], "correct":"Pickling"},
{"question": "What is the national dish of America?", "answers": ["Hamburger", "Steak", "Pizza", "Hot Dog"], "correct":"Hamburger"},
{"question": "What country exports the most food?", "answers": ["China", "Mexico", "Britain", "United States"], "correct":"United States"},
{"question": "Where was beer invented?", "answers": ["Greece", "Mesopotamia", "Italy", "Ireland"], "correct":"Mesopotamia"},
{"question": "When was McDonalds invented?", "answers": ["1955", "1925", "1895", "1965"], "correct":"1955"},
{"question": "What is the proper title for a person who makes pizzas in a pizzeria?", "answers": ["Pizzarian", "Pizza Chef", "Pizzaiolo", "Pizal"], "correct":"Pizzaiolo"},
{"question": "What is name of the scale used to measure the spicy heat of peppers?", "answers": ["Fahrenheit", "Heat Units", "Covin Units", "Scoville Units"], "correct":"Scoville Units"},
{"question": "Where did chopsticks originate?", "answers": ["Japan", "China", "Russia", "Malaysia"], "correct":"China"},
{"question": "What is the national dish of Italy?", "answers": ["Ragu al Bolognese", "Spaghetti", "Pizza", "Chicken Alfredo"], "correct":"Chicken Alfredo"},
{"question": "What is the national dish of Japan?", "answers": ["Sushi", "Mochi", "Yakitori", "Curry Rice"], "correct":"Curry Rice"},
{"question": "What is the national dish of Mexico?", "answers": ["Huevos Rancheros", "Burrito", "Mole Poblano", "Enchiladas"], "correct":"Mole Poblano"},
{"question": "What part of the body do carrots help?", "answers": ["Bones", "Eyes", "Brain", "Muscles"], "correct":"Eyes"},
{"question": "What is the main ingredient of traditional Japanese miso soup", "answers": ["Tofu", "Seaweed", "Fish Stock", "Miso Paste"], "correct":"Miso Paste"},
{"question": "Which of these is NOT a type of pasta?", "answers": ["Lento", "Ditalini", "Fusilli", "Cavatappi"], "correct":"Lento"},
{"question": "Which of these is NOT a type of cheese?", "answers": ["Gouda", "Brie", "Mozzarella", "Meringue"], "correct":"Meringue"},
{"question": "Which of these is a common ingredient in Caesar salad dressing?", "answers": ["Yogurt", "Anchovies", "Mayonnaise", "Horseradish"], "correct":"Anchovies"},
{"question": "What type of bean is used in traditional chili con carne?", "answers": ["Pinto Beans", "Kidney Beans", "Black Beans", "Lima Beans"], "correct":"Kidney Beans"},
{"question": "Which fruit is known as the 'king of fruits' and is known for its strong odor?", "answers": ["Mango", "Papaya", "Durian", "Starfruit"], "correct":"Durian"},
{"question": "Which type of meat is typically used in a traditional shepherd's pie?", "answers": ["Chicken", "Lamb", "Duck", "Pork"], "correct":"Lamb"},
{"question": "What is the main ingredient in the Japanese dish, tempura?", "answers": ["Tuna", "Tofu", "Salmon", "Shrimp"], "correct":"Shrimp"},
{"question": "What is the main ingredient in the hummus?", "answers": ["Chickpeas", "Lentils", "Avocado", "Cabbage"], "correct":"Chickpeas"},
{"question": "Which Italian coffee drink is made with equal parts espresso, steamed milk, and milk foam?", "answers": ["Latte", "Macchiato", "Cappuccino", "Cortado"], "correct":"Cappuccino"},
{"question": "Which of these is not a fruit?", "answers": ["Cucumber", "Avocado", "Pumpkin", "Beets"], "correct":"Beets"},
{"question": "What is the most stolen grocery store item?", "answers": ["Cheese", "Lettuce", "Carrots", "Milk"], "correct":"Cheese"},
{"question": "What country drinks the most coffee?", "answers": ["Brazil", "Finland", "United States", "Spain"], "correct":"Finland"},
{"question": "What chocolate bar is the global bestseller?", "answers": ["Hershey's", "Reese's", "Snickers", "Twix"], "correct":"Snickers"},
{"question": "What country produces the most coffee?", "answers": ["Venezuela", "Cuba", "India", "Brazil"], "correct":"Brazil"},
{"question": "What is 'corn' translated into Spanish?", "answers": ["Maíz", "Coruna", "Amarillo", "Guisante"], "correct":"Maíz"},
{"question": "What popular dessert was made by mistake?", "answers": ["Brownies", "Chocolate Chip Cookies", "Fudge", "Gelato"], "correct":"Chocolate Chip Cookies"},
{"question": "Where did the Caesar salad originate", "answers": ["Italy", "Greece", "Mexico", "Portugal"], "correct":"Mexico"},
{"question": "Which country consumes the most chocolate?", "answers": ["United Kingdom", "United States", "Switzerland", "Finland"], "correct":"Switzerland"},
{"question": "What is the primary ingredient in a tamale?", "answers": ["Wheat", "Potato", "Rice", "Corn"], "correct":"Corn"},
{"question": "What is the most common pizza topping?", "answers": ["Pepperoni", "Green Peppers", "Banana Peppers", "Onions"], "correct":"Pepperoni"},
{"question": "Which alcoholic beverage is made from fermented rice?", "answers": ["Whisky", "Sake", "Tequila", "Rum"], "correct":"Sake"},
{"question": "What was ketchup used as during the mid 1800s?", "answers": ["Chip Dip", "Shaving Cream", "Medicine", "Insect Repellent"], "correct":"Medicine"},
{"question": "Where did bubble tea originate?", "answers": ["China", "Singapore", "Japan", "Taiwan"], "correct":"Taiwan"},
{"question": "In a medical emergency, coconut water can be used as what?", "answers": ["Blood Plasma", "Antibiotic", "Sleep Aid", "Muscle Relaxant"], "correct":"Blood Plasma"},
{"question": "What amount comes in a 'baker's dozen'?", "answers": ["10", "12", "13", "15"], "correct":"13"},
{"question": "Which country introduced chopsticks?", "answers": ["Japan", "Taiwan", "China", "Korea"], "correct":"China"},
{"question": "Approximately, how many seeds are in a strawberry?", "answers": ["50", "100", "200", "500"], "correct":"200"},
{"question": "Prunes are made from dried...", "answers": ["Plums", "Pears", "Grapes", "Pomegranates"], "correct":"Plums"},
{"question": "What is the hottest pepper in the world?", "answers": ["Ghost Pepper", "Carolina Reaper", "Trinidad Scorpion", "Pepper X"], "correct":"Pepper X"},

]
