questions = [
{"question": "What is the national liquor of America?", "answers": ["Beer", "Red Wine", "Bourbon", "Whisky"], "correct":"Bourbon"},
{"question": "What is the national dish of Italy?", "answers": ["Spaghetti", "Pizza", "Linguine", "Bolognese"], "correct":"Bolognese"},
{"question": "\"I'm lovin' it\" is the slogan of which restaurant?", "answers": ["Taco Bell", "McDonalds", "Pizza Hut", "Burger King"], "correct":"McDonalds"},
{"question": "What is the most popular food in the world?", "answers": ["Chicken", "Pizza", "Rice", "French Fries"], "correct":"Chicken"},
{"question": "What happens if you put a rotten egg in water?", "answers": ["It will float", "It will sink", "It will stay in the middle"], "correct":"It will float"},
{"question": "Which country serves as the home of the largest farm in the world?", "answers": ["United States", "Japan", "Mexico", "China"], "correct":"China"},
{"question": "What ingredient in bread causes it to rise?", "answers": ["Yeast", "Gluten", "Flour", "Salt"], "correct":"Yeast"},
{"question": "Which of the following is not a name for a hot dog?", "answers": ["Frankfurter", "Wiener", "Weenie", "Porker Stick"], "correct":"Porker Stick"},
{"question": "Potato chips/crisps were originally called what?", "answers": ["Potato Thins", "Potato Skins", "Saratoga Chips", "Charleston Chips"], "correct":"Saratoga Chips"},
{"question": "In movies and literature, which herb is often used as a weapon to kill vampires?", "answers": ["Thymes", "Garlic", "Chamomile", "Rosemary"], "correct":"Garlic"},
{"question": "In which country did tacos originate?", "answers": ["Spain", "Mexico", "Ecuador", "United States"], "correct":"Mexico"},
{"question": "Which fruit was considered poisonous in Medieval times?", "answers": ["Raspberry", "Cherry", "Watermelon", "Tomato"], "correct":"Tomato"},
{"question": "In which country did paella originate?", "answers": ["Spain", "Mexico", "Ecuador", "United States"], "correct":"Spain"},
{"question": "Where did the pineapple plant originate?", "answers": ["Hawaii", "South America", "Mexico", "Asia"], "correct":"South America"},
{"question": "People used to salt meat taken on ships so it would stay good longer.", "answers": ["True", "False"], "correct":"True"},
{"question": "What is cinnamon made out of?", "answers": ["Bark off a tree", "Leaves", "Cinnmaum Plant", "Salt and Ginger"], "correct":"Bark off a tree"},
{"question": "Where did Iced Tea Originate?", "answers": ["United Kingdom", "China", "Japan", "United States"], "correct":"United States"},
{"question": "In ancient China, which meat was reserved only for the Emperor?", "answers": ["Chicken", "Pork", "Beef", "Mutton"], "correct":"Pork"},
{"question": "In which country did sushi originate?", "answers": ["China", "Japan", "France", "United States"], "correct":"Japan"}
]
